import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const schemaSource = readFileSync(new URL('./schema.ts', import.meta.url), 'utf8')
const serverSource = readFileSync(new URL('./index.ts', import.meta.url), 'utf8')
const organizationsSource = readFileSync(new URL('./organizations.ts', import.meta.url), 'utf8')
const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const organizationWorkbenchSource = readFileSync(new URL('../src/components/organization-workbench.tsx', import.meta.url), 'utf8')
const apiSource = readFileSync(new URL('../src/api.ts', import.meta.url), 'utf8')

test('project transfer requests are persisted as pending in-app approvals', () => {
  assert.match(schemaSource, /create table if not exists project_transfer_requests/u)
  assert.match(schemaSource, /target_open_id text not null/u)
  assert.match(schemaSource, /check \(status in \('pending', 'accepted', 'declined', 'expired', 'revoked', 'delivery_failed'\)\)/u)
  assert.match(schemaSource, /idx_project_transfer_requests_pending_project[\s\S]+where status = 'pending'/u)
  assert.match(schemaSource, /create table if not exists project_transfer_callback_events/u)
})

test('organization project transfer has a direct, organization-admin-only path', () => {
  const routeStart = serverSource.indexOf("app.post('/api/organizations/:organizationId/projects/:projectId/transfer'")
  const routeEnd = serverSource.indexOf("app.post('/api/project-transfers/:transferId/respond'", routeStart)
  assert.ok(routeStart >= 0)
  assert.ok(routeEnd > routeStart)
  const route = serverSource.slice(routeStart, routeEnd)
  assert.match(route, /lockResourceManager\(client, 'project', projectId, userId\)/u)
  assert.match(route, /lockOrganizationResourceManager\(client, organizationId, userId\)/u)
  assert.match(route, /status = 'revoked'/u)
  assert.match(route, /update projects set user_id = \$1/u)
  assert.match(route, /update project_memberships set owner_user_id = \$1/u)
  assert.match(route, /project\.transfer\.direct/u)
  assert.doesNotMatch(route, /target_user_id.*pending/u)
  assert.match(apiSource, /transferOrganizationProjectOwnership\(/u)
  assert.match(organizationWorkbenchSource, /transferOrganizationProjectOwnership\(detail\.id, project\.id, targetUserId\)/u)
  assert.match(organizationWorkbenchSource, /无需对方确认/u)
})

test('project transfer records the original owner while permitting organization resource administration', () => {
  const routeStart = serverSource.indexOf("app.post('/api/projects/:projectId/transfer'")
  const routeEnd = serverSource.indexOf("app.delete('/api/projects/:projectId'", routeStart)
  assert.ok(routeStart >= 0)
  assert.ok(routeEnd > routeStart)
  const route = serverSource.slice(routeStart, routeEnd)

  assert.match(route, /lockResourceManager\(client, 'project', projectId, userId\)/u)
  assert.match(route, /previous_owner_user_id/u)
  assert.match(route, /access\.ownerUserId/u)
  assert.match(route, /const organizationId = Number\(request\.body\?\.organizationId\)/u)
  assert.match(route, /user_id in \(\$2::bigint, \$3::bigint\)/u)
  assert.match(route, /lockTransferProject\(client, transferId\)/u)
  assert.match(route, /canCompleteProjectTransfer\(client/u)
  assert.doesNotMatch(route, /Only organization projects can be transferred/u)
  assert.doesNotMatch(route, /access\.role !== 'owner'/u)
  assert.doesNotMatch(route, /resolveFeishuOpenIdByEmail/u)
  assert.doesNotMatch(route, /buildProjectTransferRequestCard/u)
  assert.match(route, /hashProjectTransferToken\(token\)/u)
  assert.match(route, /update project_transfer_requests[\s\S]+set status = 'revoked'[\s\S]+where project_id = \$1 and status = 'pending'/u)
  assert.doesNotMatch(route, /sendFeishuMessage/u)
})

test('notification center can accept or decline a project transfer', () => {
  const routeStart = serverSource.indexOf("app.post('/api/project-transfers/:transferId/respond'")
  const routeEnd = serverSource.indexOf("app.delete('/api/projects/:projectId'", routeStart)
  assert.ok(routeStart >= 0)
  assert.ok(routeEnd > routeStart)
  const route = serverSource.slice(routeStart, routeEnd)
  assert.match(route, /ensureUserId\(request, response\)/u)
  assert.match(route, /target_user_id = \$2/u)
  assert.match(route, /status !== 'pending'/u)
  assert.match(route, /expires_at\.getTime\(\) <= Date\.now\(\)/u)
  assert.match(route, /activeOwners\.rows\.length !== 2/u)
  assert.match(route, /update projects\s+set user_id = \$1/u)
  assert.match(route, /update project_memberships\s+set owner_user_id = \$1/u)
  assert.match(route, /delete from project_memberships/u)
  assert.match(route, /organization_audit_events/u)
  assert.match(route, /getNotifications\(userId\)/u)
  assert.match(serverSource, /projectTransfersResult/u)
  assert.match(serverSource, /kind: 'project_transfer'/u)
  assert.match(appSource, /notifications\.projectTransfers/u)
  assert.match(appSource, /拒绝项目「\$\{item\.transferProjectName\}/u)
  assert.match(appSource, /同意项目「\$\{item\.transferProjectName\}/u)
})

test('legacy Feishu project transfer approval remains identity-bound', () => {
  assert.match(organizationsSource, /project_transfer_accept/u)
  assert.match(organizationsSource, /project_transfer_decline/u)
  assert.match(organizationsSource, /row\.target_open_id !== operatorOpenId/u)
  assert.match(organizationsSource, /row\.token_hash !== hashProjectTransferToken\(transferToken\)/u)
  assert.match(organizationsSource, /select pg_advisory_xact_lock\(hashtextextended\(\$1, 0\)\)/u)
  assert.match(organizationsSource, /user_id in \(\$2::bigint, \$3::bigint\)/u)
  assert.match(organizationsSource, /activeOwners\.rows\.length !== 2/u)
  assert.match(organizationsSource, /update projects\s+set user_id = \$1, updated_at = now\(\)\s+where id = \$2 and user_id = \$3/u)
  assert.doesNotMatch(organizationsSource, /update projects\s+set user_id[\s\S]{0,200}organization_id/u)
  assert.match(organizationsSource, /update project_memberships[\s\S]+set owner_user_id = \$1[\s\S]+where project_id = \$2/u)
  assert.match(organizationsSource, /delete from project_memberships[\s\S]+where project_id = \$1 and invited_user_id = \$2/u)
  assert.match(organizationsSource, /insert into project_memberships[\s\S]+status = 'active'/u)
  assert.match(organizationsSource, /on conflict \(project_id, invited_email_lookup\) where invited_email_lookup is not null do update/u)
  assert.match(organizationsSource, /project_transfer_callback_events/u)
  assert.match(organizationsSource, /buildProjectTransferStatusCard/u)
})

test('project basket exposes transfer for any owned project and selects a shared organization', () => {
  assert.match(apiSource, /export function requestProjectTransfer\([\s\S]+payload: \{ organizationId: number; targetUserId: number \}/u)
  assert.match(apiSource, /\/api\/projects\/\$\{projectId\}\/transfer/u)
  assert.match(appSource, /fetchOrganizations\(\)/u)
  assert.match(appSource, /fetchOrganization\(organizationId\)/u)
  assert.match(appSource, /requestProjectTransfer\(transferringProject\.id, \{ organizationId, targetUserId \}\)/u)
  assert.match(appSource, /<UserSwitch \/> 项目转移/u)
  assert.match(appSource, /onRespondProjectTransfer=\{respondProjectTransfer\}/u)
  assert.match(appSource, /可在通知中心确认/u)
  assert.match(appSource, /项目转移申请/u)
  assert.match(appSource, /共同组织/u)
  assert.match(appSource, /if \(!transferringProject \|\| !value\.trim\(\)\) return/u)
  assert.match(appSource, /!Number\.isSafeInteger\(organizationId\) \|\| organizationId <= 0/u)
  assert.doesNotMatch(appSource, /canTransferProject=\{Boolean\(project\.organizationId\)\}/u)
})
