import { authorizeDelivery, deliveryAccess, listDeliveryMembers, requireDeliveryAssignee, auditDelivery, lockDeliveryProject, ProjectDeliveryError } from './project-delivery.ts'
import { deliveryCapabilities, type DeliveryCapabilities, type ProjectDeliveryMember } from '../shared/project-delivery.ts'
import type { PoolClient, QueryResultRow } from 'pg'
import { decryptText, encryptText } from './crypto.ts'
import { pool, query } from './db.ts'
import {
  createPackageItemDownloadUrl,
  isPackageMarketObjectKeyAllowedForRule,
  type PackageMarketRule,
} from './package-market.ts'
import { getDepartedUserIds } from './user-lifecycle.ts'
import { getPlatformConfigSnapshot } from './platform-config-runtime.ts'
import { getPackageMarketRulesForConfigRevision } from './platform-package-rules.ts'

export type ProjectPackageEventType = 'init' | 'upgrade'
export type ProjectPackageEventStatus = 'draft' | 'delivering' | 'delivered'
export type ProjectPackageOperationStatus = 'failed' | 'pending' | 'success'
export type ProjectPackageOperationKind = 'document' | 'event'

export type ProjectPackageItemInput = {
  arch: string
  channel: string
  channelLabel: string
  objectKey: string
  objectLastModified?: string
  packageName: string
  sizeBytes?: number
  sourcePackageId: string
  sourcePackageName: string
  version: string
}

export type ProjectPackageDocumentInput = {
  content: string
  packageName?: string
  relatedTodoIds?: number[]
  scope: 'event' | 'package'
  title: string
}

export type ProjectPackageEventSaveAction = 'publish' | 'save_draft'

export class ProjectPackageEventError extends Error {
  readonly status: 400 | 403 | 404 | 409

  constructor(message: string, status: 400 | 403 | 404 | 409) {
    super(message)
    this.name = 'ProjectPackageEventError'
    this.status = status
  }
}

export type ProjectPackageItem = {
  arch: string
  channel: string
  channelLabel: string
  createdAt: string
  id: number
  objectKey: string
  objectLastModified?: string
  packageName: string
  sizeBytes?: number
  sourceConfigRevision?: number
  sourcePackageId: string
  sourcePackageName: string
  version: string
}

export type ProjectPackageOperation = {
  autoGenerated: boolean
  completed: boolean
  content: string
  createdAt: string
  eventId: number
  groupId: number | null
  id: number
  kind: ProjectPackageOperationKind
  label: string
  relatedTodoIds: number[]
  relatedTodoNotes: Record<number, string>
  status: ProjectPackageOperationStatus
  title: string
  updatedAt: string
}

export type ProjectPackageGroup = {
  id: number
  items: ProjectPackageItem[]
  operations: ProjectPackageOperation[]
  packageName: string
}

export type ProjectPackageEventComment = {
  authorName: string
  authorUserId?: number
  canEdit?: boolean
  content: string
  createdAt: string
  id: number
  updatedAt: string
}

export type ProjectPackageMentionableMember = {
  id: number
  name: string
}

export type ProjectPackageEvent = {
  capabilities: DeliveryCapabilities
  createdByName?: string
  publishedByName?: string
  completedByName?: string
  completedByUserId?: number
  completedAt?: string
  assignedAt?: string
  assignedByName?: string
  assignedByUserId?: number
  assigneeName?: string
  assigneeUserId?: number
  comments: ProjectPackageEventComment[]
  createdAt: string
  deliveryDate: string
  deliveryEndAt: string
  deliveryStartAt: string
  groups: ProjectPackageGroup[]
  id: number
  operations: ProjectPackageOperation[]
  publishedAt?: string
  publishedByUserId?: number
  status: ProjectPackageEventStatus
  title: string
  type: ProjectPackageEventType
  updatedAt: string
}

export type ProjectPackageTimeline = {
  canPlanDelivery: boolean
  deliveryMembers: ProjectDeliveryMember[]
  departedUserIds: number[]
  events: ProjectPackageEvent[]
  mentionableMembers: ProjectPackageMentionableMember[]
  projectId: number
}

type EventRow = {
  creator_name: string | null
  publisher_name: string | null
  completer_name: string | null
  completed_by_user_id: string | null
  completed_at: Date | null
  assigned_at: Date | null
  assigned_by_user_id: string | null
  assignee_display_name: string | null
  assignee_email: string | null
  assignee_user_id: string | null
  assigner_display_name: string | null
  assigner_email: string | null
  created_at: Date
  delivery_date: Date | string | null
  delivery_end_at: Date
  delivery_start_at: Date
  id: string
  published_at: Date | null
  published_by_user_id: string | null
  status: ProjectPackageEventStatus
  title: string
  type: ProjectPackageEventType
  updated_at: Date
}

type GroupRow = {
  created_at: Date
  id: string
  package_name: string
  project_package_event_id: string
}

type ItemRow = {
  arch: string
  channel: string
  channel_label: string
  created_at: Date
  id: string
  object_key: string
  object_last_modified: Date | null
  project_package_group_id: string
  size_bytes: string | null
  source_config_revision: string | null
  source_package_id: string
  source_package_name: string
  version: string
}

type OperationRow = {
  auto_generated: boolean
  completed: boolean
  content: string
  created_at: Date
  id: string
  kind: ProjectPackageOperationKind
  label: string
  project_package_event_id: string
  project_package_group_id: string | null
  status: ProjectPackageOperationStatus
  title: string
  updated_at: Date
}

type OperationTodoRow = {
  note: string
  project_package_operation_id: string
  todo_id: string
}

type PackageEventCommentRow = {
  author_display_name: string | null
  author_email: string | null
  author_user_id: string | null
  content: string
  created_at: Date
  id: string
  project_package_event_id: string
  updated_at: Date | null
}

type MentionableMemberRow = {
  display_name: string | null
  email: string | null
  id: string
}

type ProjectOperationTodoLinkRow = {
  operation_id: string
  todo_id: string | null
}

type OperationRelatedTodoExportRow = {
  note: string | null
  note_author_display_name: string | null
  note_author_email: string | null
  operation_note_author_display_name: string | null
  operation_note_author_email: string | null
  operation_id: string
  todo_id: string
  todo_title: string
}

type OperationRelatedTodoExportDetail = {
  note: string
  noteAuthorName: string
  title: string
  todoId: number
}

type NormalizedProjectPackageItem = {
  arch: string
  channel: string
  channelLabel: string
  objectKey: string
  objectLastModified: Date | null
  packageName: string
  sizeBytes: number | null
  sourcePackageId: string
  sourcePackageName: string
  version: string
}

type NormalizedProjectPackageDocument = {
  content: string
  packageName: string
  relatedTodoIds: number[]
  scope: 'event' | 'package'
  title: string
}

async function withTransaction<T>(operation: (client: PoolClient) => Promise<T>) {
  const client = await pool.connect()
  try {
    await client.query('begin')
    const result = await operation(client)
    await client.query('commit')
    return result
  } catch (error) {
    await client.query('rollback')
    throw error
  } finally {
    client.release()
  }
}

function formatDateTime(value: Date | string) {
  const date = value instanceof Date ? value : new Date(value)
  const parts = new Intl.DateTimeFormat('zh-CN', {
    day: '2-digit',
    hour: '2-digit',
    hour12: false,
    minute: '2-digit',
    month: '2-digit',
    second: '2-digit',
    timeZone: 'Asia/Shanghai',
    year: 'numeric',
  }).formatToParts(date)
  const pick = (type: Intl.DateTimeFormatPartTypes) =>
    parts.find((part) => part.type === type)?.value ?? ''
  return `${pick('year')}-${pick('month')}-${pick('day')} ${pick('hour')}:${pick('minute')}:${pick('second')}`
}

function formatDate(value: Date | string) {
  const date = value instanceof Date ? value : new Date(value)
  const parts = new Intl.DateTimeFormat('en-CA', {
    day: '2-digit',
    month: '2-digit',
    timeZone: 'Asia/Shanghai',
    year: 'numeric',
  }).formatToParts(date)
  const pick = (type: Intl.DateTimeFormatPartTypes) =>
    parts.find((part) => part.type === type)?.value ?? ''
  return `${pick('year')}-${pick('month')}-${pick('day')}`
}

function normalizeDeliveryDate(value: unknown) {
  const rawDate = String(value ?? '').trim()
  if (!/^\d{4}-\d{2}-\d{2}$/.test(rawDate)) {
    throw new ProjectPackageEventError('Delivery date must use YYYY-MM-DD', 400)
  }
  const date = new Date(`${rawDate}T00:00:00+08:00`)
  if (Number.isNaN(date.getTime()) || formatDate(date) !== rawDate) {
    throw new ProjectPackageEventError('Delivery date is invalid', 400)
  }
  return rawDate
}

function parseDeliveryDateTime(value: unknown, label: string) {
  const rawValue = String(value ?? '').trim()
  const match = rawValue.match(
    /^(\d{4})[-/](\d{1,2})[-/](\d{1,2})[T ](\d{1,2}):(\d{2})(?::(\d{2}))?$/,
  )
  if (!match) {
    throw new ProjectPackageEventError(`${label} must use YYYY-MM-DDTHH:mm`, 400)
  }
  const [, year, month, day, hour, minute, second = '00'] = match
  const normalized = `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}T${hour.padStart(2, '0')}:${minute}:${second}+08:00`
  const date = new Date(normalized)
  const expectedLocalValue = `${normalized.slice(0, 10)} ${normalized.slice(11, 19)}`
  if (Number.isNaN(date.getTime()) || formatDateTime(date) !== expectedLocalValue) {
    throw new ProjectPackageEventError(`${label} is invalid`, 400)
  }
  return date
}

function normalizeDeliveryWindow(params: {
  deliveryDate?: string
  deliveryEndAt?: string
  deliveryStartAt?: string
}) {
  let startAt: Date
  let endAt: Date
  if (params.deliveryStartAt != null || params.deliveryEndAt != null) {
    if (params.deliveryStartAt == null || params.deliveryEndAt == null) {
      throw new ProjectPackageEventError('Delivery start and end times are both required', 400)
    }
    startAt = parseDeliveryDateTime(params.deliveryStartAt, 'Delivery start time')
    endAt = parseDeliveryDateTime(params.deliveryEndAt, 'Expected delivery completion time')
  } else {
    const deliveryDate = normalizeDeliveryDate(params.deliveryDate)
    startAt = parseDeliveryDateTime(`${deliveryDate}T00:00`, 'Delivery start time')
    endAt = parseDeliveryDateTime(`${deliveryDate}T23:59:59`, 'Expected delivery completion time')
  }
  if (startAt >= endAt) {
    throw new ProjectPackageEventError('Delivery start time must be earlier than expected completion time', 400)
  }
  return {
    deliveryDate: formatDate(endAt),
    deliveryEndAt: endAt,
    deliveryStartAt: startAt,
  }
}

function displayUserName(row?: { display_name?: string | null; email?: string | null } | null) {
  if (!row) return ''
  return row.display_name || row.email || ''
}

function eventTypeLabel(type: ProjectPackageEventType) {
  return type === 'init' ? '初始化安装' : '升级'
}

function formatLocalizedDateTimeString(value: string) {
  const match = String(value ?? '')
    .trim()
    .match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})[ T](\d{2}):(\d{2}):(\d{2})$/)
  if (!match) return null
  const [, year, month, day, hour, minute, second] = match
  return `${Number(year)}/${Number(month)}/${Number(day)} ${hour}:${minute}:${second}`
}

function formatExportDateTime(value: Date | string) {
  if (typeof value === 'string') {
    const localized = formatLocalizedDateTimeString(value)
    if (localized) {
      return localized
    }
  }
  return new Date(value).toLocaleString('zh-CN', {
    hour12: false,
    timeZone: 'Asia/Shanghai',
  })
}

function formatExportDateTimeForFileName(value: Date | string) {
  const parts = new Intl.DateTimeFormat('zh-CN', {
    day: '2-digit',
    hour: '2-digit',
    hour12: false,
    minute: '2-digit',
    month: '2-digit',
    second: '2-digit',
    timeZone: 'Asia/Shanghai',
    year: 'numeric',
  }).formatToParts(new Date(value))
  const pick = (type: Intl.DateTimeFormatPartTypes) =>
    parts.find((part) => part.type === type)?.value ?? ''
  return [
    pick('year'),
    pick('month'),
    pick('day'),
    pick('hour'),
    pick('minute'),
    pick('second'),
  ].join('-')
}

function sanitizeExportFileName(value: string) {
  const cleaned = Array.from(String(value ?? ''), (char) => {
    if ('<>:"/\\|?*'.includes(char)) return '-'
    const code = char.charCodeAt(0)
    return code >= 0 && code <= 31 ? '-' : char
  }).join('')
  return cleaned
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'record'
}

export function ensureProjectPackageEventType(value: unknown): ProjectPackageEventType {
  return value === 'init' ? 'init' : 'upgrade'
}

export function ensureProjectPackageEventStatus(
  value: unknown,
  publishedAt?: unknown,
): ProjectPackageEventStatus {
  if (publishedAt !== undefined) {
    if (!publishedAt) return 'draft'
    return value === 'delivered' || value === 'success' ? 'delivered' : 'delivering'
  }
  if (value === 'delivered' || value === 'success') return 'delivered'
  if (value === 'delivering' || value === 'failed') return 'delivering'
  return 'draft'
}

export function ensureProjectPackageOperationStatus(value: unknown): ProjectPackageOperationStatus {
  if (value === 'success' || value === 'failed') return value
  return 'pending'
}

export function ensureProjectPackageOperationKind(value: unknown): ProjectPackageOperationKind {
  return value === 'event' ? 'event' : 'document'
}

function normalizeText(value: unknown, max = 200) {
  return String(value ?? '').trim().slice(0, max)
}

function normalizeProjectPackageItems(items: ProjectPackageItemInput[]) {
  if (items.length === 0) {
    throw new ProjectPackageEventError('At least one package item is required', 400)
  }

  return items.map((item, index): NormalizedProjectPackageItem => {
    const packageName = normalizeText(item.packageName, 160)
    const objectKey = normalizeText(item.objectKey, 400)
    if (!packageName || !objectKey) {
      throw new ProjectPackageEventError(`Package item ${index + 1} requires packageName and objectKey`, 400)
    }

    let objectLastModified: Date | null = null
    if (item.objectLastModified) {
      objectLastModified = new Date(item.objectLastModified)
      if (Number.isNaN(objectLastModified.getTime())) {
        throw new ProjectPackageEventError(`Package item ${index + 1} has an invalid objectLastModified`, 400)
      }
    }

    let sizeBytes: number | null = null
    if (item.sizeBytes != null) {
      sizeBytes = Math.round(item.sizeBytes)
      if (!Number.isSafeInteger(sizeBytes) || sizeBytes < 0) {
        throw new ProjectPackageEventError(`Package item ${index + 1} has an invalid sizeBytes`, 400)
      }
    }

    return {
      arch: normalizeText(item.arch, 32) || 'amd64',
      channel: normalizeText(item.channel, 32) || 'release',
      channelLabel: normalizeText(item.channelLabel, 40),
      objectKey,
      objectLastModified,
      packageName,
      sizeBytes,
      sourcePackageId: normalizeText(item.sourcePackageId, 120),
      sourcePackageName: normalizeText(item.sourcePackageName || packageName, 160),
      version: normalizeText(item.version, 80),
    }
  })
}

function normalizeProjectPackageDocuments(
  documents: ProjectPackageDocumentInput[],
  packageNames: Set<string>,
  allowIncomplete: boolean,
) {
  const normalized = documents.map((document, index): NormalizedProjectPackageDocument => {
    const scope = document.scope === 'package' ? 'package' : 'event'
    const title = normalizeText(document.title, 120)
    const content = String(document.content ?? '').trim()
    const packageName = scope === 'package' ? normalizeText(document.packageName, 160) : ''
    const relatedTodoIds = normalizeTodoIds(document.relatedTodoIds)
    if (!allowIncomplete && (!title || !content)) {
      throw new ProjectPackageEventError(`Document ${index + 1} requires title and content`, 400)
    }
    if (scope === 'package' && (!packageName || !packageNames.has(packageName))) {
      throw new ProjectPackageEventError(`Document ${index + 1} references an unavailable package`, 400)
    }
    return { content, packageName, relatedTodoIds, scope, title }
  })

  const scopes = new Set<string>()
  for (const document of normalized) {
    const key = document.scope === 'event' ? 'event' : `package:${document.packageName}`
    if (scopes.has(key)) throw new ProjectPackageEventError(`Only one document is allowed for ${key}`, 400)
    scopes.add(key)
  }
  return normalized
}

function normalizePositiveIds(value: unknown) {
  if (!Array.isArray(value)) return []
  return Array.from(
    new Set(
      value
        .map((item) => Number(item))
        .filter((item) => Number.isInteger(item) && item > 0),
    ),
  )
}

function normalizeTodoIds(value: unknown) {
  return normalizePositiveIds(value)
}

function normalizeTodoNotes(value: unknown) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {}
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .map(([todoId, note]) => [Number(todoId), String(note ?? '').trim().slice(0, 1000)] as const)
      .filter(([todoId]) => Number.isInteger(todoId) && Number(todoId) > 0),
  ) as Record<number, string>
}

async function touchEvent(eventId: number, client?: PoolClient) {
  const sql = `
    update project_package_events
    set updated_at = now()
    where id = $1
  `
  if (client) {
    await client.query(sql, [eventId])
    return
  }
  await query(sql, [eventId])
}

async function findEventMeta(eventId: number, projectId: number, client?: PoolClient) {
  const sql = `
    select id, type, published_at
    from project_package_events
    where id = $1 and project_id = $2
    ${client ? 'for update' : ''}
  `
  const result = client
    ? await client.query<{ id: string; published_at: Date | null; type: ProjectPackageEventType }>(sql, [eventId, projectId])
    : await query<{ id: string; published_at: Date | null; type: ProjectPackageEventType }>(sql, [eventId, projectId])
  return result.rows[0] ?? null
}

function ensureUnpublishedEvent<T extends { published_at: Date | null }>(event: T | null): T {
  if (!event) throw new ProjectPackageEventError('Event not found', 404)
  if (event.published_at) throw new ProjectPackageEventError('Published events are read-only', 409)
  return event
}

async function findGroupMeta(groupId: number, projectId: number, client?: PoolClient) {
  const sql = `
    select e.id as event_id,
           e.published_at,
           g.id as group_id,
           g.package_name
    from project_package_groups g
    join project_package_events e on e.id = g.project_package_event_id
    where g.id = $1 and e.project_id = $2
    ${client ? 'for update of e' : ''}
  `
  const result = client
    ? await client.query<{ event_id: string; group_id: string; package_name: string; published_at: Date | null }>(sql, [groupId, projectId])
    : await query<{ event_id: string; group_id: string; package_name: string; published_at: Date | null }>(sql, [groupId, projectId])
  return result.rows[0] ?? null
}

async function findOperationMeta(operationId: number, projectId: number, client?: PoolClient) {
  const sql = `
    select o.id,
           o.project_package_event_id as event_id,
           o.project_package_group_id as group_id,
           o.completed,
           e.published_at
    from project_package_operations o
    join project_package_events e on e.id = o.project_package_event_id
    where o.id = $1
      and e.project_id = $2
      and (
        o.project_package_group_id is null
        or exists (
          select 1
          from project_package_groups g
          where g.id = o.project_package_group_id
            and g.project_package_event_id = o.project_package_event_id
        )
      )
    ${client ? 'for update of e' : ''}
  `
  const result = client
    ? await client.query<{
        completed: boolean
        event_id: string
        group_id: string | null
        id: string
        published_at: Date | null
      }>(sql, [operationId, projectId])
    : await query<{
        completed: boolean
        event_id: string
        group_id: string | null
        id: string
        published_at: Date | null
      }>(sql, [operationId, projectId])
  return result.rows[0] ?? null
}

async function ensureProjectTodoIds(projectId: number, todoIds: number[], client?: PoolClient) {
  const normalizedTodoIds = normalizeTodoIds(todoIds)
  if (normalizedTodoIds.length === 0) return []

  const sql = `
    select id
    from todos
    where project_id = $1
      and id = any($2::bigint[])
  `
  const result = client
    ? await client.query<{ id: string }>(sql, [projectId, normalizedTodoIds])
    : await query<{ id: string }>(sql, [projectId, normalizedTodoIds])
  const foundTodoIds = new Set(result.rows.map((row) => Number(row.id)))
  if (foundTodoIds.size !== normalizedTodoIds.length) {
    throw new ProjectPackageEventError('Some todos were not found in this project', 400)
  }
  return normalizedTodoIds
}

async function replaceOperationTodoLinks(
  client: PoolClient,
  operationId: number,
  authorUserId: number,
  todoIds: number[],
  todoNotes: Record<number, string> = {},
) {
  await client.query(
    `
    delete from project_package_operation_todos
    where project_package_operation_id = $1
    `,
    [operationId],
  )

  for (const todoId of todoIds) {
    const note = String(todoNotes[todoId] ?? '').trim()
    const encryptedNote = note ? encryptText(note) : ''
    await client.query(
      `
      insert into project_package_operation_todos (
        project_package_operation_id,
        todo_id,
        note,
        note_author_user_id
      )
      values ($1, $2, $3, $4)
      on conflict (project_package_operation_id, todo_id) do update
        set note = excluded.note,
            note_author_user_id = case
              when excluded.note <> '' then excluded.note_author_user_id
              else project_package_operation_todos.note_author_user_id
            end
      `,
      [operationId, todoId, encryptedNote, note ? authorUserId : null],
    )
  }
}

async function syncOperationTodoNotes(
  client: PoolClient,
  operationId: number,
  authorUserId: number,
  todoIds: number[],
  todoNotes: Record<number, string> = {},
) {
  const normalizedTodoIds = normalizeTodoIds(todoIds)

  await client.query(
    `
    delete from todo_notes
    where source_operation_id = $1
      and todo_id <> all($2::bigint[])
    `,
    [operationId, normalizedTodoIds.length > 0 ? normalizedTodoIds : [0]],
  )

  for (const todoId of normalizedTodoIds) {
    const note = String(todoNotes[todoId] ?? '').trim()
    if (!note) {
      await client.query(
        `
        delete from todo_notes
        where todo_id = $1
          and source_operation_id = $2
        `,
        [todoId, operationId],
      )
      continue
    }

    await client.query(
      `
      insert into todo_notes (todo_id, author_user_id, content, source_operation_id)
      values ($1, $2, $3, $4)
      on conflict (todo_id, source_operation_id)
        where source_operation_id is not null
      do update
        set content = excluded.content,
            author_user_id = excluded.author_user_id,
            updated_at = now()
      `,
      [todoId, authorUserId, encryptText(note), operationId],
    )
  }
}

async function setTodosDoneState(projectId: number, todoIds: number[], done: boolean) {
  const normalizedTodoIds = await ensureProjectTodoIds(projectId, todoIds)
  if (normalizedTodoIds.length === 0) return

  await query(
    `
    update todos
    set done = $1,
        updated_at = now()
    where project_id = $2
      and id = any($3::bigint[])
    `,
    [done, projectId, normalizedTodoIds],
  )
}

async function listProjectOperationTodoLinks(projectId: number) {
  const result = await query<ProjectOperationTodoLinkRow>(
    `
    select o.id as operation_id,
           t.todo_id
    from project_package_operations o
    join project_package_events e on e.id = o.project_package_event_id
    left join project_package_operation_todos t
      on t.project_package_operation_id = o.id
    where e.project_id = $1
    `,
    [projectId],
  )
  return result.rows
}

function buildProjectCompletionGraph(rows: ProjectOperationTodoLinkRow[]) {
  const operationToTodos = new Map<number, number[]>()
  const todoToOperations = new Map<number, number[]>()

  for (const row of rows) {
    const operationId = Number(row.operation_id)
    if (!operationToTodos.has(operationId)) {
      operationToTodos.set(operationId, [])
    }
    if (!row.todo_id) continue
    const todoId = Number(row.todo_id)
    operationToTodos.set(operationId, [...(operationToTodos.get(operationId) ?? []), todoId])
    todoToOperations.set(todoId, [...(todoToOperations.get(todoId) ?? []), operationId])
  }

  return { operationToTodos, todoToOperations }
}

function collectConnectedProjectCompletionIds(
  graph: ReturnType<typeof buildProjectCompletionGraph>,
  seeds: {
    operationIds?: number[]
    todoIds?: number[]
  },
) {
  const operationIds = new Set(normalizePositiveIds(seeds.operationIds ?? []))
  const todoIds = new Set(normalizePositiveIds(seeds.todoIds ?? []))
  const operationQueue = [...operationIds]
  const todoQueue = [...todoIds]

  while (operationQueue.length > 0 || todoQueue.length > 0) {
    while (operationQueue.length > 0) {
      const operationId = operationQueue.shift()
      if (operationId == null) continue
      for (const todoId of graph.operationToTodos.get(operationId) ?? []) {
        if (todoIds.has(todoId)) continue
        todoIds.add(todoId)
        todoQueue.push(todoId)
      }
    }

    while (todoQueue.length > 0) {
      const todoId = todoQueue.shift()
      if (todoId == null) continue
      for (const operationId of graph.todoToOperations.get(todoId) ?? []) {
        if (operationIds.has(operationId)) continue
        operationIds.add(operationId)
        operationQueue.push(operationId)
      }
    }
  }

  return {
    operationIds: [...operationIds],
    todoIds: [...todoIds],
  }
}

async function setOperationsCompletedState(projectId: number, operationIds: number[], completed: boolean) {
  const normalizedOperationIds = normalizePositiveIds(operationIds)
  if (normalizedOperationIds.length === 0) return

  await query(
    `
    update project_package_operations o
    set completed = $1,
        updated_at = now()
    from project_package_events e
    where o.project_package_event_id = e.id
      and e.project_id = $2
      and o.id = any($3::bigint[])
    `,
    [completed, projectId, normalizedOperationIds],
  )
}

async function touchEventsForOperations(projectId: number, operationIds: number[]) {
  const normalizedOperationIds = normalizePositiveIds(operationIds)
  if (normalizedOperationIds.length === 0) return

  await query(
    `
    update project_package_events e
    set updated_at = now()
    where e.project_id = $1
      and exists (
        select 1
        from project_package_operations o
        where o.project_package_event_id = e.id
          and o.id = any($2::bigint[])
      )
    `,
    [projectId, normalizedOperationIds],
  )
}

export async function syncProjectPackageCompletionState(params: {
  completed: boolean
  operationIds?: number[]
  projectId: number
  todoIds?: number[]
}) {
  const seedOperationIds = normalizePositiveIds(params.operationIds ?? [])
  const seedTodoIds = normalizePositiveIds(params.todoIds ?? [])

  if (seedOperationIds.length === 0 && seedTodoIds.length === 0) {
    return {
      operationIds: [],
      todoIds: [],
    }
  }

  const graph = buildProjectCompletionGraph(await listProjectOperationTodoLinks(params.projectId))
  const connectedIds = collectConnectedProjectCompletionIds(graph, {
    operationIds: seedOperationIds,
    todoIds: seedTodoIds,
  })

  if (connectedIds.operationIds.length > 0) {
    await setOperationsCompletedState(params.projectId, connectedIds.operationIds, params.completed)
  }
  if (connectedIds.todoIds.length > 0) {
    await setTodosDoneState(params.projectId, connectedIds.todoIds, params.completed)
  }
  if (connectedIds.operationIds.length > 0) {
    await touchEventsForOperations(params.projectId, connectedIds.operationIds)
  }

  return connectedIds
}

async function findOrCreateGroup(
  client: PoolClient,
  eventId: number,
  packageName: string,
) {
  const result = await client.query<{ id: string }>(
    `
    insert into project_package_groups (project_package_event_id, package_name)
    values ($1, $2)
    on conflict (project_package_event_id, package_name) do update
      set package_name = excluded.package_name
    returning id
    `,
    [eventId, packageName],
  )
  return Number(result.rows[0].id)
}

async function maybeSeedGroupOperation(
  client: PoolClient,
  eventId: number,
  groupId: number,
  eventType: ProjectPackageEventType,
  createdByUserId: number,
) {
  await client.query(
    `
    insert into project_package_operations (
      project_package_event_id,
      project_package_group_id,
      kind,
      title,
      label,
      content,
      auto_generated,
      created_by_user_id
    )
    select $1, $2, 'event', '', $3, '', true, $4
    where not exists (
      select 1
      from project_package_operations
      where project_package_group_id = $2
    )
    on conflict (project_package_group_id) where auto_generated do nothing
    `,
    [eventId, groupId, eventTypeLabel(eventType), createdByUserId],
  )
}

function textValue(value: unknown, fallback = '-') {
  const normalized = String(value ?? '').trim()
  return normalized || fallback
}

function packageDownloadUrlValue(
  item: Pick<ProjectPackageItem, 'channel' | 'objectKey' | 'sourceConfigRevision' | 'sourcePackageId'>,
  rulesByRevision?: ReadonlyMap<number, readonly PackageMarketRule[]>,
) {
  try {
    const channel = item.channel === 'ci' || item.channel === 'release' ? item.channel : null
    const rules = item.sourceConfigRevision
      ? rulesByRevision?.get(item.sourceConfigRevision)
      : undefined
    if (item.sourceConfigRevision && !rules) {
      return '临时下载链接生成失败：历史平台配置不可用'
    }
    if (!channel || !isPackageMarketObjectKeyAllowedForRule({
      channel,
      objectKey: item.objectKey,
      packageId: item.sourcePackageId,
      rules,
    })) {
      return '临时下载链接生成失败：安装包对象路径与安装包规则不匹配'
    }
    return createPackageItemDownloadUrl(item.objectKey)
  } catch (error) {
    return `临时下载链接生成失败：${String((error as Error).message ?? error)}`
  }
}

function packageFileName(objectKey: string, fallback: string) {
  const segments = String(objectKey ?? '')
    .split('/')
    .map((segment) => segment.trim())
    .filter(Boolean)
  return segments.at(-1) || textValue(fallback)
}

function escapeMarkdownLinkLabel(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\[/g, '\\[').replace(/\]/g, '\\]')
}

function normalizeExportNoteText(value: unknown, fallback = '未填写') {
  const normalized = String(value ?? '').trim()
  if (!normalized) return fallback
  return normalized
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join(' / ')
}

function buildPackageTimelineNodes(group: ProjectPackageGroup) {
  const itemNodes = group.items.map((item) => ({
    type: 'package-operation' as const,
    createdAt: item.createdAt,
    item,
  }))
  const operationNodes = group.operations.map((operation) => ({
    type: operation.kind,
    createdAt: operation.createdAt,
    operation,
  }))
  return [...itemNodes, ...operationNodes].sort((left, right) =>
    left.createdAt.localeCompare(right.createdAt),
  )
}

function buildOperationMarkdown(
  operation: ProjectPackageOperation,
  relatedTodoDetails: OperationRelatedTodoExportDetail[] = [],
  level = '###',
  options: {
    headingNumber?: string
    listStyle?: boolean
    relatedTodoHeadingNumber?: string
  } = {},
) {
  const createdAt = formatExportDateTime(operation.createdAt)
  const relatedTodoLines = relatedTodoDetails.flatMap((detail, index) => {
    const lines = [
      `- 关联待办：${textValue(detail.title, `#${detail.todoId}`)}`,
      `  - 备注作者：${textValue(detail.noteAuthorName, '未填写')}`,
      `  - 备注内容：${normalizeExportNoteText(detail.note)}`,
    ]
    return index === 0 ? lines : ['', ...lines]
  })
  const relatedTodoBlock = relatedTodoLines.length > 0
    ? [
      '',
      `${level} ${options.relatedTodoHeadingNumber ? `${options.relatedTodoHeadingNumber} ` : ''}关联待办说明`,
      '',
      ...relatedTodoLines,
    ]
    : []
  if (operation.kind === 'document') {
    return [
      `${level} ${options.headingNumber ? `${options.headingNumber} ` : ''}文档：${textValue(operation.title, '未命名操作文档')}`,
      '',
      `- 时间：${createdAt}`,
      '',
      textValue(operation.content, '无内容'),
      ...relatedTodoBlock,
    ]
  }

  const eventLabel = textValue(operation.label, '操作事件')
  const operationTitle = textValue(operation.title, '')
  if (options.listStyle) {
    const lines = [`- ${createdAt} · ${eventLabel}`]
    if (operation.content) {
      if (operationTitle && operationTitle !== eventLabel) {
        lines.push('', `  - ${operationTitle}`)
      }
      lines.push('', textValue(operation.content, '无内容'))
    }
    if (relatedTodoLines.length > 0) {
      lines.push('', ...relatedTodoLines)
    }
    return lines
  }

  const detailLevel = `${level}#`
  const lines = [
    `${level} ${options.headingNumber ? `${options.headingNumber} ` : ''}${createdAt}`,
    '',
    `${detailLevel} ${eventLabel}`,
  ]
  if (operation.content) {
    if (operationTitle && operationTitle !== eventLabel) {
      lines.push('', `${detailLevel}# ${operationTitle}`, '', operation.content)
    } else {
      lines.push('', operation.content)
    }
  }
  lines.push(...relatedTodoBlock)
  return lines
}

function buildPackageTimelineMarkdown(
  group: ProjectPackageGroup,
  relatedTodoDetailsByOperation: Map<number, OperationRelatedTodoExportDetail[]>,
  rulesByRevision: ReadonlyMap<number, readonly PackageMarketRule[]>,
  options: {
    headingLevel?: string
    sectionNumber?: string
  } = {},
) {
  const headingLevel = options.headingLevel ?? '##'
  const lines: string[] = []
  const nodes = buildPackageTimelineNodes(group)
  const packageOperations = nodes.filter((node) => node.type !== 'package-operation')
  const packageRecords = nodes.filter((node) => node.type === 'package-operation')
  const headingPrefix = options.sectionNumber ? `${options.sectionNumber}. ` : ''
  const linkSectionPrefix = options.sectionNumber ? `${options.sectionNumber}.1 ` : ''

  if (packageRecords.length > 0) {
    const details = Array.from(
      new Set(
        packageRecords.map((node) => {
          if (node.type !== 'package-operation') return ''
          const item = node.item
          return [textValue(item.channelLabel), textValue(item.arch), textValue(item.version, '未知版本')]
            .filter(Boolean)
            .join(' · ')
        }).filter(Boolean),
      ),
    )
    lines.push(`${headingLevel} ${headingPrefix}${group.packageName} · ${details.join('；')}`, '')
    lines.push(`${headingLevel}# ${linkSectionPrefix}临时下载链接`, '')
    packageRecords.forEach((node) => {
      if (node.type !== 'package-operation') return
      const item = node.item
      const fileName = packageFileName(item.objectKey, item.packageName)
      const downloadUrl = packageDownloadUrlValue(item, rulesByRevision)
      if (downloadUrl.startsWith('临时下载链接生成失败：')) {
        lines.push(`- ${textValue(fileName)}：${downloadUrl}`)
        return
      }
      lines.push(`- [${escapeMarkdownLinkLabel(textValue(fileName))}](${downloadUrl})`)
    })
    lines.push('')
  } else {
    lines.push(`${headingLevel} ${headingPrefix}${group.packageName}`, '')
  }

  if (packageOperations.length === 0) {
    lines.push('暂无时间线记录。')
    return lines
  }

  packageOperations.forEach((node) => {
    lines.push(
      ...buildOperationMarkdown(
        node.operation,
        relatedTodoDetailsByOperation.get(node.operation.id) ?? [],
        `${headingLevel}#`,
        { listStyle: true },
      ),
      '',
    )
  })

  return lines
}

function countPackageItems(timeline: ProjectPackageTimeline) {
  return timeline.events.reduce(
    (total, event) =>
      total + event.groups.reduce((eventTotal, group) => eventTotal + group.items.length, 0),
    0,
  )
}

function buildProjectPackageTimelineMarkdown(
  projectName: string,
  ownerName: string,
  timeline: ProjectPackageTimeline,
  relatedTodoDetailsByOperation: Map<number, OperationRelatedTodoExportDetail[]>,
  rulesByRevision: ReadonlyMap<number, readonly PackageMarketRule[]>,
) {
  const lines = [
    `# ${textValue(projectName, '未命名项目')} 项目时间线`,
    '',
    `- 项目负责人：${textValue(ownerName, '未填写')}`,
    `- 安装包操作记录：${countPackageItems(timeline)} 条`,
    `- 导出时间：${formatExportDateTime(new Date())}`,
  ]

  if (timeline.events.length === 0) {
    lines.push('', '暂无项目事件。')
    return `${lines.join('\n')}\n`
  }

  timeline.events.forEach((event, eventIndex) => {
    if (eventIndex > 0) {
      lines.push('', '---', '')
    }
    lines.push(...buildProjectPackageEventMarkdown(event, relatedTodoDetailsByOperation, rulesByRevision))
  })

  return `${lines.join('\n')}\n`
}

function buildProjectPackageEventMarkdown(
  event: ProjectPackageEvent,
  relatedTodoDetailsByOperation: Map<number, OperationRelatedTodoExportDetail[]>,
  rulesByRevision: ReadonlyMap<number, readonly PackageMarketRule[]>,
) {
  const lines: string[] = [
    '',
    `## ${formatExportDateTime(event.createdAt)}`,
    '',
    `### ${textValue(event.title, '未命名事件')}`,
    '',
    `- 交付人：${textValue(event.assigneeName, '未指派')}`,
    `- 交付时间：${event.deliveryStartAt} ~ ${event.deliveryEndAt}`,
    '',
    '### 1. 操作文档',
    '',
  ]
  if (event.operations.length === 0) {
    lines.push('暂无操作文档。', '')
  } else {
    let operationHeadingIndex = 1
    event.operations.forEach((operation) => {
      const relatedTodoDetails = relatedTodoDetailsByOperation.get(operation.id) ?? []
      const headingNumber = `1.${operationHeadingIndex}`
      const relatedTodoHeadingNumber = relatedTodoDetails.length > 0
        ? `1.${operationHeadingIndex + 1}`
        : undefined
      lines.push(
        ...buildOperationMarkdown(
          operation,
          relatedTodoDetails,
          '####',
          {
            headingNumber,
            relatedTodoHeadingNumber,
          },
        ),
        '',
      )
      operationHeadingIndex += relatedTodoDetails.length > 0 ? 2 : 1
    })
  }

  if (event.groups.length === 0) {
    lines.push('暂无安装包。', '')
    return lines
  }

  event.groups
    .slice()
    .sort((left, right) => left.packageName.localeCompare(right.packageName, 'zh-CN'))
    .forEach((group, groupIndex) => {
      lines.push(
        ...buildPackageTimelineMarkdown(group, relatedTodoDetailsByOperation, rulesByRevision, {
          headingLevel: '###',
          sectionNumber: String(groupIndex + 2),
        }),
        '',
      )
    })
  return lines
}

export async function getProjectPackageTimeline(projectId: number, userId = 0) {
  const [
    eventsResult,
    groupsResult,
    itemsResult,
    operationsResult,
    operationTodosResult,
    commentsResult,
    mentionableMembersResult,
  ] = await Promise.all([
    query<EventRow>(
      `
      select e.id,
             coalesce(nullif(creator.display_name, ''), creator.email) as creator_name,
             coalesce(nullif(publisher.display_name, ''), publisher.email) as publisher_name,
             coalesce(nullif(completer.display_name, ''), completer.email) as completer_name,
             e.completed_by_user_id, e.completed_at,
             e.type,
             e.status,
             e.title,
             e.assignee_user_id,
             e.assigned_by_user_id,
             e.assigned_at,
             e.delivery_date,
             e.delivery_start_at,
             e.delivery_end_at,
             e.published_at,
             e.published_by_user_id,
             e.created_at,
             e.updated_at,
             assignee.email as assignee_email,
             assignee.display_name as assignee_display_name,
             assigner.email as assigner_email,
             assigner.display_name as assigner_display_name
      from project_package_events e
      left join users creator on creator.id = e.created_by_user_id
      left join users publisher on publisher.id = e.published_by_user_id
      left join users completer on completer.id = e.completed_by_user_id
      left join users assignee on assignee.id = e.assignee_user_id
      left join users assigner on assigner.id = e.assigned_by_user_id
      where e.project_id = $1
      order by e.created_at asc, e.id asc
      `,
      [projectId],
    ),
    query<GroupRow>(
      `
      select g.id, g.project_package_event_id, g.package_name, g.created_at
      from project_package_groups g
      join project_package_events e on e.id = g.project_package_event_id
      where e.project_id = $1
      order by g.created_at asc, g.id asc
      `,
      [projectId],
    ),
    query<ItemRow>(
      `
      select i.id,
             i.project_package_group_id,
             i.source_package_id,
             i.source_package_name,
             i.channel,
             i.channel_label,
             i.arch,
             i.version,
             i.object_key,
             i.object_last_modified,
             i.size_bytes::text,
             i.source_config_revision,
             i.created_at
      from project_package_items i
      join project_package_groups g on g.id = i.project_package_group_id
      join project_package_events e on e.id = g.project_package_event_id
      where e.project_id = $1
      order by i.created_at asc, i.id asc
      `,
      [projectId],
    ),
    query<OperationRow>(
      `
      select o.id,
             o.project_package_event_id,
             o.project_package_group_id,
             o.kind,
             o.status,
             o.title,
             o.label,
             o.content,
             o.completed,
             o.auto_generated,
             o.created_at,
             o.updated_at
      from project_package_operations o
      join project_package_events e on e.id = o.project_package_event_id
      where e.project_id = $1
        and (
          o.project_package_group_id is null
          or exists (
            select 1
            from project_package_groups g
            where g.id = o.project_package_group_id
              and g.project_package_event_id = o.project_package_event_id
          )
        )
      order by o.created_at asc, o.id asc
      `,
      [projectId],
    ),
    query<OperationTodoRow>(
      `
      select t.project_package_operation_id,
             t.todo_id,
             t.note
      from project_package_operation_todos t
      join project_package_operations o on o.id = t.project_package_operation_id
      join project_package_events e on e.id = o.project_package_event_id
      where e.project_id = $1
      order by t.created_at asc, t.todo_id asc
      `,
      [projectId],
    ),
    query<PackageEventCommentRow>(
      `
      select c.id,
             c.project_package_event_id,
             c.author_user_id,
             c.content,
             c.created_at,
             c.updated_at,
             author.email as author_email,
             author.display_name as author_display_name
      from project_package_event_comments c
      join project_package_events e on e.id = c.project_package_event_id
      left join users author on author.id = c.author_user_id
      where e.project_id = $1
      order by c.created_at asc, c.id asc
      `,
      [projectId],
    ),
    query<MentionableMemberRow>(
      `
      select u.id, u.email, u.display_name
      from users u
      where (
        u.id = (select p.user_id from projects p where p.id = $1)
        or exists (
          select 1 from project_memberships pm
          where pm.project_id = $1 and pm.invited_user_id = u.id and pm.status = 'active'
        )
        or exists (
          select 1 from projects p
          join organization_memberships om on om.organization_id = p.organization_id
          where p.id = $1 and om.user_id = u.id and om.status = 'active'
        )
      )
      order by lower(coalesce(nullif(u.display_name, ''), u.email)), u.id
      `,
      [projectId],
    ),
  ])

  const groupsByEvent = new Map<number, ProjectPackageGroup[]>()
  const groupMap = new Map<number, ProjectPackageGroup>()
  const groupEventById = new Map<number, number>()
  for (const row of groupsResult.rows) {
    const group: ProjectPackageGroup = {
      id: Number(row.id),
      packageName: row.package_name,
      items: [],
      operations: [],
    }
    const eventId = Number(row.project_package_event_id)
    const groups = groupsByEvent.get(eventId) ?? []
    groups.push(group)
    groupsByEvent.set(eventId, groups)
    groupMap.set(group.id, group)
    groupEventById.set(group.id, eventId)
  }

  for (const row of itemsResult.rows) {
    const group = groupMap.get(Number(row.project_package_group_id))
    if (!group) continue
    group.items.push({
      id: Number(row.id),
      sourcePackageId: row.source_package_id,
      sourcePackageName: row.source_package_name,
      packageName: group.packageName,
      channel: row.channel,
      channelLabel: row.channel_label,
      arch: row.arch,
      version: row.version,
      objectKey: row.object_key,
      objectLastModified: row.object_last_modified
        ? formatDateTime(row.object_last_modified)
        : undefined,
      sizeBytes: row.size_bytes ? Number(row.size_bytes) : undefined,
      sourceConfigRevision: row.source_config_revision ? Number(row.source_config_revision) : undefined,
      createdAt: formatDateTime(row.created_at),
    })
  }

  const relatedTodoIdsByOperation = new Map<number, number[]>()
  const relatedTodoNotesByOperation = new Map<number, Record<number, string>>()
  for (const row of operationTodosResult.rows) {
    const operationId = Number(row.project_package_operation_id)
    const todoIds = relatedTodoIdsByOperation.get(operationId) ?? []
    todoIds.push(Number(row.todo_id))
    relatedTodoIdsByOperation.set(operationId, todoIds)
    const todoNotes = relatedTodoNotesByOperation.get(operationId) ?? {}
    todoNotes[Number(row.todo_id)] = row.note ? decryptText(row.note) : ''
    relatedTodoNotesByOperation.set(operationId, todoNotes)
  }

  const commentsByEvent = new Map<number, ProjectPackageEventComment[]>()
  for (const row of commentsResult.rows) {
    const comments = commentsByEvent.get(Number(row.project_package_event_id)) ?? []
    comments.push({
      authorName: displayUserName({
        email: row.author_email,
        display_name: row.author_display_name,
      }),
      authorUserId: row.author_user_id ? Number(row.author_user_id) : undefined,
      content: decryptText(row.content),
      createdAt: formatDateTime(row.created_at),
      id: Number(row.id),
      updatedAt: formatDateTime(row.updated_at ?? row.created_at),
    })
    commentsByEvent.set(Number(row.project_package_event_id), comments)
  }

  const mentionableMembers: ProjectPackageMentionableMember[] = mentionableMembersResult.rows.map(
    (row) => ({
      id: Number(row.id),
      name: displayUserName({ email: row.email, display_name: row.display_name }),
    }),
  )

  const eventOperationsByEvent = new Map<number, ProjectPackageOperation[]>()
  for (const row of operationsResult.rows) {
    const operation: ProjectPackageOperation = {
      id: Number(row.id),
      eventId: Number(row.project_package_event_id),
      groupId: row.project_package_group_id == null ? null : Number(row.project_package_group_id),
      kind: row.kind,
      title: decryptText(row.title),
      label: row.label,
      content: row.content ? decryptText(row.content) : '',
      status: ensureProjectPackageOperationStatus(row.status),
      relatedTodoIds: relatedTodoIdsByOperation.get(Number(row.id)) ?? [],
      relatedTodoNotes: relatedTodoNotesByOperation.get(Number(row.id)) ?? {},
      completed: row.completed,
      autoGenerated: row.auto_generated,
      createdAt: formatDateTime(row.created_at),
      updatedAt: formatDateTime(row.updated_at),
    }
    if (row.project_package_group_id) {
      const groupId = Number(row.project_package_group_id)
      const group = groupMap.get(groupId)
      // Keep the event and package relationship together. Legacy rows can
      // contain mismatched IDs; never surface such a document under another
      // package's timeline.
      if (group && groupEventById.get(groupId) === operation.eventId) {
        group.operations.push(operation)
      }
    } else {
      const eventId = Number(row.project_package_event_id)
      const operations = eventOperationsByEvent.get(eventId) ?? []
      operations.push(operation)
      eventOperationsByEvent.set(eventId, operations)
    }
  }

  const access = await deliveryAccess(projectId, userId)
  const deliveryMembers = await listDeliveryMembers(projectId)
  return {
    canPlanDelivery: access.canPlan,
    deliveryMembers,
    departedUserIds: await getDepartedUserIds(),
    projectId,
    events: eventsResult.rows.map((row) => ({
      capabilities: deliveryCapabilities(access, { published: Boolean(row.published_at), delivered: row.status === 'delivered', assigneeUserId: row.assignee_user_id ? Number(row.assignee_user_id) : null }, userId),
      createdByName: row.creator_name ?? undefined,
      publishedByName: row.publisher_name ?? undefined,
      completedByName: row.completer_name ?? undefined,
      completedByUserId: row.completed_by_user_id ? Number(row.completed_by_user_id) : undefined,
      completedAt: row.completed_at ? formatDateTime(row.completed_at) : undefined,
      assignedAt: row.assigned_at ? formatDateTime(row.assigned_at) : undefined,
      assignedByName: row.assigned_by_user_id
        ? displayUserName({
            email: row.assigner_email,
            display_name: row.assigner_display_name,
          })
        : undefined,
      assignedByUserId: row.assigned_by_user_id ? Number(row.assigned_by_user_id) : undefined,
      assigneeName: row.assignee_user_id
        ? displayUserName({
            email: row.assignee_email,
            display_name: row.assignee_display_name,
          })
        : undefined,
      assigneeUserId: row.assignee_user_id ? Number(row.assignee_user_id) : undefined,
      comments: commentsByEvent.get(Number(row.id)) ?? [],
      id: Number(row.id),
      publishedAt: row.published_at ? formatDateTime(row.published_at) : undefined,
      publishedByUserId: row.published_by_user_id ? Number(row.published_by_user_id) : undefined,
      type: row.type,
      status: ensureProjectPackageEventStatus(row.status, row.published_at),
      title: decryptText(row.title),
      createdAt: formatDateTime(row.created_at),
      deliveryDate: row.delivery_date ? formatDate(row.delivery_date) : formatDate(row.created_at),
      deliveryEndAt: formatDateTime(row.delivery_end_at),
      deliveryStartAt: formatDateTime(row.delivery_start_at),
      updatedAt: formatDateTime(row.updated_at),
      operations: eventOperationsByEvent.get(Number(row.id)) ?? [],
      groups: groupsByEvent.get(Number(row.id)) ?? [],
    })),
    mentionableMembers,
  } satisfies ProjectPackageTimeline
}

export async function saveProjectPackageEvent(params: {
  action: ProjectPackageEventSaveAction
  assignedByUserId: number
  assigneeUserId: number | null
  createdByUserId: number
  deliveryDate?: string
  deliveryEndAt?: string
  deliveryStartAt?: string
  documents: ProjectPackageDocumentInput[]
  eventId?: number
  items: ProjectPackageItemInput[]
  projectId: number
  title: string
  type: ProjectPackageEventType
  validatePackageItems?: (
    client: PoolClient,
    items: Array<Pick<ProjectPackageItemInput, 'channel' | 'objectKey' | 'sourcePackageId'>>,
  ) => Promise<void>
}) {
  const title = normalizeText(params.title, 120)
  if (!title) throw new ProjectPackageEventError('Event title is required', 400)
  const deliveryWindow = normalizeDeliveryWindow(params)
  const items = params.items.length > 0 ? normalizeProjectPackageItems(params.items) : []
  const duplicateObjectKeys = items.filter(
    (item, index) => items.findIndex((candidate) => candidate.objectKey === item.objectKey) !== index,
  )
  if (duplicateObjectKeys.length > 0) {
    throw new ProjectPackageEventError('Package items must be unique', 400)
  }
  const packageNames = new Set(items.map((item) => item.packageName))
  const documents = normalizeProjectPackageDocuments(
    params.documents,
    packageNames,
    params.action === 'save_draft',
  )
  if (params.action === 'publish' && !documents.some((document) => document.scope === 'event')) {
    throw new ProjectPackageEventError('An event document is required before publishing', 400)
  }
  const sourceConfigRevision = getPlatformConfigSnapshot().revision

  return withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.createdByUserId, 'plan', params.eventId == null ? undefined : { eventId: params.eventId })
    await requireDeliveryAssignee(client, params.projectId, params.assigneeUserId, params.action === 'publish')
    await ensureProjectTodoIds(
      params.projectId,
      documents.flatMap((document) => document.relatedTodoIds),
      client,
    )
    await params.validatePackageItems?.(client, items)

    let eventId = params.eventId
    if (eventId != null) {
      ensureUnpublishedEvent(await findEventMeta(eventId, params.projectId, client))
      const updated = await client.query(
        `
        update project_package_events
        set type = $1,
            title = $2,
            assignee_user_id = $3,
            assigned_by_user_id = $4,
            delivery_date = $5::date,
            delivery_start_at = $6::timestamptz,
            delivery_end_at = $7::timestamptz,
            updated_at = now()
        where id = $8
          and project_id = $9
          and published_at is null
        `,
        [
          params.type,
          encryptText(title),
          params.assigneeUserId,
          params.assignedByUserId,
          deliveryWindow.deliveryDate,
          deliveryWindow.deliveryStartAt,
          deliveryWindow.deliveryEndAt,
          eventId,
          params.projectId,
        ],
      )
      if (updated.rowCount !== 1) {
        throw new ProjectPackageEventError('Published events are read-only', 409)
      }
    } else {
      const created = await client.query<{ id: string }>(
        `
        insert into project_package_events (
          project_id,
          type,
          status,
          title,
          created_by_user_id,
          assignee_user_id,
          assigned_by_user_id,
          delivery_date,
          delivery_start_at,
          delivery_end_at
        )
        values ($1, $2, 'draft', $3, $4, $5, $6, $7::date, $8::timestamptz, $9::timestamptz)
        returning id
        `,
        [
          params.projectId,
          params.type,
          encryptText(title),
          params.createdByUserId,
          params.assigneeUserId,
          params.assignedByUserId,
          deliveryWindow.deliveryDate,
          deliveryWindow.deliveryStartAt,
          deliveryWindow.deliveryEndAt,
        ],
      )
      eventId = Number(created.rows[0].id)
    }
    if (eventId == null) throw new ProjectPackageEventError('Event could not be saved', 409)
    const persistedEventId = eventId

    await client.query(
      'delete from project_package_operations where project_package_event_id = $1',
      [persistedEventId],
    )
    await client.query(
      'delete from project_package_groups where project_package_event_id = $1',
      [persistedEventId],
    )

    const groupIds = new Map<string, number>()
    for (const item of items) {
      let groupId = groupIds.get(item.packageName)
      if (!groupId) {
        groupId = await findOrCreateGroup(client, persistedEventId, item.packageName)
        groupIds.set(item.packageName, groupId)
      }
      await client.query(
        `
        insert into project_package_items (
          project_package_group_id,
          source_package_id,
          source_package_name,
          channel,
          channel_label,
          arch,
          version,
          object_key,
          object_last_modified,
          size_bytes,
          created_by_user_id,
          source_config_revision
        )
        values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
        `,
        [
          groupId,
          item.sourcePackageId,
          item.sourcePackageName,
          item.channel,
          item.channelLabel,
          item.arch,
          item.version,
          item.objectKey,
          item.objectLastModified,
          item.sizeBytes,
          params.createdByUserId,
          sourceConfigRevision,
        ],
      )
    }

    for (const groupId of groupIds.values()) {
      await maybeSeedGroupOperation(client, persistedEventId, groupId, params.type, params.createdByUserId)
    }

    for (const document of documents) {
      const groupId = document.scope === 'package'
        ? groupIds.get(document.packageName) ?? null
        : null
      const insertedDocument = await client.query<{ id: string }>(
        `
        insert into project_package_operations (
          project_package_event_id,
          project_package_group_id,
          kind,
          status,
          title,
          label,
          content,
          completed,
          auto_generated,
          created_by_user_id
        )
        values ($1, $2, 'document', 'pending', $3, '', $4, false, false, $5)
        returning id
        `,
        [persistedEventId, groupId, encryptText(document.title), encryptText(document.content), params.createdByUserId],
      )
      await replaceOperationTodoLinks(
        client,
        Number(insertedDocument.rows[0].id),
        params.createdByUserId,
        document.relatedTodoIds,
      )
    }

    let published = false
    if (params.action === 'publish') {
      const publication = await client.query(
        `
        update project_package_events
        set status = 'delivering',
            published_at = now(),
            published_by_user_id = $1,
            assigned_at = now(),
            updated_at = now()
        where id = $2
          and project_id = $3
          and published_at is null
        `,
        [params.assignedByUserId, persistedEventId, params.projectId],
      )
      if (publication.rowCount !== 1) {
        throw new ProjectPackageEventError('Published events are read-only', 409)
      }
      published = true
    }

    return { eventId: persistedEventId, published }
  })
}

export async function completeProjectPackageEvent(params: { eventId: number; projectId: number; userId: number }) {
  await withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.userId, 'canComplete', { eventId: params.eventId })
    const result = await client.query(`update project_package_events set status = 'delivered', completed_by_user_id = $1,
      completed_at = now(), updated_at = now() where id = $2 and project_id = $3
      and published_at is not null
      and status = 'delivering'`,
    [params.userId, params.eventId, params.projectId])
    if (result.rowCount !== 1) throw new ProjectDeliveryError('任务状态已变化，请刷新后重试', 409)
  })
}

export async function reassignProjectPackageEvent(params: {
  projectId: number; eventId: number; userId: number; assigneeUserId: number; previousAssigneeUserId: number | null; reason: string
}) {
  const reason = params.reason.trim()
  if (!reason || reason.length > 1000) throw new ProjectDeliveryError('请填写 1–1000 字的交接原因', 400)
  await withTransaction(async (client) => {
    const event = await authorizeDelivery(client, params.projectId, params.userId, 'canReassign', { eventId: params.eventId })
    if ((event?.assignee_user_id ? Number(event.assignee_user_id) : null) !== params.previousAssigneeUserId) {
      throw new ProjectDeliveryError('执行负责人已变化，请刷新后重新确认', 409)
    }
    await requireDeliveryAssignee(client, params.projectId, params.assigneeUserId, true)
    if (Number(event?.assignee_user_id) === params.assigneeUserId) throw new ProjectDeliveryError('请选择另一位执行负责人', 400)
    const organizationId = await lockDeliveryProject(client, params.projectId)
    await client.query(`update project_package_events set assignee_user_id = $1, assigned_by_user_id = $2,
      assigned_at = now(), updated_at = now() where id = $3 and project_id = $4`,
    [params.assigneeUserId, params.userId, params.eventId, params.projectId])
    if (organizationId) await auditDelivery(client, organizationId, params.projectId, params.userId, 'delivery.reassigned', {
      eventId: params.eventId, previousAssigneeUserId: params.previousAssigneeUserId, assigneeUserId: params.assigneeUserId, reason,
    })
    await client.query(`insert into project_package_event_comments (project_package_event_id, author_user_id, content)
      values ($1, $2, $3)`, [params.eventId, params.userId, encryptText(`转交执行负责人：${reason}`)])
  })
}

export async function updateProjectPackageEvent(params: {
  assignedByUserId: number
  assigneeUserId?: number | null
  client?: PoolClient
  eventId: number
  deliveryDate?: string
  deliveryEndAt?: string
  deliveryStartAt?: string
  projectId: number
  status?: ProjectPackageEventStatus
  title?: string
  type?: ProjectPackageEventType
}) {
  const updates: string[] = []
  const values: unknown[] = []
  if (params.title != null) {
    const title = normalizeText(params.title, 120)
    if (!title) throw new Error('Event title is required')
    values.push(encryptText(title))
    updates.push(`title = $${values.length}`)
  }
  if (params.type != null) {
    values.push(params.type)
    updates.push(`type = $${values.length}`)
  }
  if (params.deliveryDate != null || params.deliveryStartAt != null || params.deliveryEndAt != null) {
    const deliveryWindow = normalizeDeliveryWindow(params)
    values.push(deliveryWindow.deliveryDate)
    updates.push(`delivery_date = $${values.length}::date`)
    values.push(deliveryWindow.deliveryStartAt)
    updates.push(`delivery_start_at = $${values.length}::timestamptz`)
    values.push(deliveryWindow.deliveryEndAt)
    updates.push(`delivery_end_at = $${values.length}::timestamptz`)
  }
  if (params.status != null) {
    values.push(ensureProjectPackageEventStatus(params.status))
    updates.push(`status = $${values.length}`)
  }
  if (Object.prototype.hasOwnProperty.call(params, 'assigneeUserId')) {
    values.push(params.assigneeUserId ?? null)
    updates.push(`assignee_user_id = $${values.length}`)
    const assigneeValueIndex = values.length
    values.push(params.assigneeUserId ? (params.assignedByUserId ?? null) : null)
    updates.push(`assigned_by_user_id = $${values.length}`)
    updates.push(
      `assigned_at = case when $${assigneeValueIndex}::bigint is null then null when assignee_user_id is distinct from $${assigneeValueIndex} then now() else assigned_at end`,
    )
  }
  if (updates.length === 0) {
    throw new Error('No supported fields to update')
  }
  values.push(params.eventId, params.projectId)
  const update = async (client: PoolClient) => {
    await authorizeDelivery(client, params.projectId, params.assignedByUserId, 'plan', { eventId: params.eventId })
    if ('assigneeUserId' in params) await requireDeliveryAssignee(client, params.projectId, params.assigneeUserId ?? null, false)
    const result = await client.query(
      `
      update project_package_events
      set ${updates.join(', ')}, updated_at = now()
      where id = $${values.length - 1}
        and project_id = $${values.length}
        and published_at is null
      `,
      values,
    )
    if (result.rowCount !== 1) throw new Error('Event not found or already published')
  }
  if (params.client) await update(params.client)
  else await withTransaction(update)
}

export async function deleteProjectPackageEvent(params: { eventId: number; projectId: number; userId: number }) {
  await withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.userId, 'plan', { eventId: params.eventId })
    await client.query('delete from project_package_events where id = $1 and project_id = $2', [params.eventId, params.projectId])
  })
}

export async function addProjectPackageItems(params: {
  createdByUserId: number
  eventId: number
  items: ProjectPackageItemInput[]
  projectId: number
  validatePackageItems?: (
    client: PoolClient,
    items: Array<Pick<ProjectPackageItemInput, 'channel' | 'objectKey' | 'sourcePackageId'>>,
  ) => Promise<void>
}) {
  const items = normalizeProjectPackageItems(params.items)
  const sourceConfigRevision = getPlatformConfigSnapshot().revision

  await withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.createdByUserId, 'plan', { eventId: params.eventId })
    await params.validatePackageItems?.(client, items)
    const event = ensureUnpublishedEvent(
      await findEventMeta(params.eventId, params.projectId, client),
    )

    for (const item of items) {
      const groupId = await findOrCreateGroup(client, params.eventId, item.packageName)
      await client.query(
        `
        insert into project_package_items (
          project_package_group_id,
          source_package_id,
          source_package_name,
          channel,
          channel_label,
          arch,
          version,
          object_key,
          object_last_modified,
          size_bytes,
          created_by_user_id,
          source_config_revision
        )
        values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
        `,
        [
          groupId,
          item.sourcePackageId,
          item.sourcePackageName,
          item.channel,
          item.channelLabel,
          item.arch,
          item.version,
          item.objectKey,
          item.objectLastModified,
          item.sizeBytes,
          params.createdByUserId,
          sourceConfigRevision,
        ],
      )
      await maybeSeedGroupOperation(
        client,
        params.eventId,
        groupId,
        event.type,
        params.createdByUserId,
      )
    }

    await touchEvent(params.eventId, client)
  })
}

export async function deleteProjectPackageGroup(params: {
  userId: number
  groupId: number
  projectId: number
}) {
  await withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.userId, 'plan', { groupId: params.groupId })
    const meta = ensureUnpublishedEvent(
      await findGroupMeta(params.groupId, params.projectId, client),
    )
    await client.query('delete from project_package_groups where id = $1', [params.groupId])
    await touchEvent(Number(meta.event_id), client)
  })
}

export async function createProjectPackageOperation(params: {
  completed?: boolean
  content?: string
  createdByUserId: number
  eventId: number
  groupId?: number | null
  kind: ProjectPackageOperationKind
  label?: string
  projectId: number
  relatedTodoIds?: number[]
  relatedTodoNotes?: Record<number, string>
  status?: ProjectPackageOperationStatus
  title?: string
}) {
  const kind = ensureProjectPackageOperationKind(params.kind)
  const title = normalizeText(params.title, 120)
  const content = String(params.content ?? '').trim()
  const relatedTodoNotes = normalizeTodoNotes(params.relatedTodoNotes)
  const completed = Boolean(params.completed)
  const status = ensureProjectPackageOperationStatus(params.status)

  if (kind === 'document' && !title) throw new Error('Operation title is required')
  if (kind === 'document' && !content) throw new Error('Operation content is required')

  await withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.createdByUserId, 'plan', { eventId: params.eventId })
    const event = ensureUnpublishedEvent(
      await findEventMeta(params.eventId, params.projectId, client),
    )
    if (params.groupId) {
      const group = await findGroupMeta(params.groupId, params.projectId, client)
      if (!group || Number(group.event_id) !== params.eventId) {
        throw new Error('Package group not found')
      }
    }

    const label = normalizeText(
      params.label ?? (kind === 'event' ? eventTypeLabel(event.type) : ''),
      120,
    )
    if (kind === 'event' && !label) throw new Error('Operation label is required')

    const relatedTodoIds = await ensureProjectTodoIds(
      params.projectId,
      params.relatedTodoIds ?? [],
      client,
    )
    const result = await client.query<{ id: string }>(
      `
      insert into project_package_operations (
        project_package_event_id,
        project_package_group_id,
        kind,
        status,
        title,
        label,
        content,
        completed,
        auto_generated,
        created_by_user_id
      )
      values ($1, $2, $3, $4, $5, $6, $7, $8, false, $9)
      returning id
      `,
      [
        params.eventId,
        params.groupId ?? null,
        kind,
        status,
        title ? encryptText(title) : '',
        label,
        content ? encryptText(content) : '',
        completed,
        params.createdByUserId,
      ],
    )
    const operationId = Number(result.rows[0].id)
    await replaceOperationTodoLinks(
      client,
      operationId,
      params.createdByUserId,
      relatedTodoIds,
      relatedTodoNotes,
    )
    await syncOperationTodoNotes(
      client,
      operationId,
      params.createdByUserId,
      relatedTodoIds,
      relatedTodoNotes,
    )

    await touchEvent(params.eventId, client)
  })
}

export async function updateProjectPackageOperation(params: {
  completed?: boolean
  content?: string
  updatedByUserId: number
  label?: string
  operationId: number
  projectId: number
  relatedTodoIds?: number[]
  relatedTodoNotes?: Record<number, string>
  status?: ProjectPackageOperationStatus
  title?: string
}) {
  const updates: string[] = []
  const values: unknown[] = []
  if (params.title != null) {
    const title = normalizeText(params.title, 120)
    if (!title) throw new Error('Operation title is required')
    values.push(encryptText(title))
    updates.push(`title = $${values.length}`)
  }
  if (params.label != null) {
    const label = normalizeText(params.label, 120)
    if (!label) throw new Error('Operation label is required')
    values.push(label)
    updates.push(`label = $${values.length}`)
  }
  if (params.content != null) {
    const content = String(params.content).trim()
    if (!content) throw new Error('Operation content is required')
    values.push(encryptText(content))
    updates.push(`content = $${values.length}`)
  }
  if (params.completed != null) {
    values.push(Boolean(params.completed))
    updates.push(`completed = $${values.length}`)
  }
  if (params.status != null) {
    values.push(ensureProjectPackageOperationStatus(params.status))
    updates.push(`status = $${values.length}`)
  }
  const shouldUpdateRelatedTodos = params.relatedTodoIds != null
  const relatedTodoNotes = shouldUpdateRelatedTodos
    ? normalizeTodoNotes(params.relatedTodoNotes)
    : {}

  if (updates.length === 0 && !shouldUpdateRelatedTodos) {
    throw new Error('No supported fields to update')
  }

  await withTransaction(async (client) => {
    await lockDeliveryProject(client, params.projectId)
    const operation = await findOperationMeta(params.operationId, params.projectId, client)
    if (!operation) throw new ProjectPackageEventError('Event not found', 404)
    await authorizeDelivery(client, params.projectId, params.updatedByUserId, operation.published_at ? 'canExecute' : 'plan', { operationId: params.operationId })
    if (operation.published_at && updates.length > 0) {
      throw new ProjectPackageEventError('Published events are read-only', 409)
    }
    const relatedTodoIds = shouldUpdateRelatedTodos
      ? await ensureProjectTodoIds(params.projectId, params.relatedTodoIds ?? [], client)
      : []

    if (updates.length > 0) {
      values.push(params.operationId)
      await client.query(
        `
        update project_package_operations
        set ${updates.join(', ')}, updated_at = now()
        where id = $${values.length}
        `,
        values,
      )
    } else {
      await client.query(
        `
        update project_package_operations
        set updated_at = now()
        where id = $1
        `,
        [params.operationId],
      )
    }

    if (shouldUpdateRelatedTodos) {
      await replaceOperationTodoLinks(
        client,
        params.operationId,
        params.updatedByUserId,
        relatedTodoIds,
        relatedTodoNotes,
      )
      await syncOperationTodoNotes(
        client,
        params.operationId,
        params.updatedByUserId,
        relatedTodoIds,
        relatedTodoNotes,
      )
    }
    await touchEvent(Number(operation.event_id), client)
  })
}

export async function deleteProjectPackageOperation(params: {
  userId: number
  operationId: number
  projectId: number
}) {
  await withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.userId, 'plan', { operationId: params.operationId })
    const operation = ensureUnpublishedEvent(
      await findOperationMeta(params.operationId, params.projectId, client),
    )
    await client.query('delete from project_package_operations where id = $1', [params.operationId])
    await touchEvent(Number(operation.event_id), client)
  })
}

export type ProjectPackageItemDownloadSource = {
  channel: string
  objectKey: string
  sourceConfigRevision: number | null
  sourcePackageId: string
}

export async function getProjectPackageItemDownloadSource(params: {
  itemId: number
  projectId: number
}) {
  const result = await query<{
    channel: string
    object_key: string
    source_config_revision: string | null
    source_package_id: string
  }>(
    `
    select i.object_key,
           i.channel,
           i.source_config_revision,
           i.source_package_id
    from project_package_items i
    join project_package_groups g on g.id = i.project_package_group_id
    join project_package_events e on e.id = g.project_package_event_id
    where i.id = $1 and e.project_id = $2
    `,
    [params.itemId, params.projectId],
  )
  const row = result.rows[0]
  return row
    ? {
        channel: row.channel,
        objectKey: row.object_key,
        sourceConfigRevision: row.source_config_revision ? Number(row.source_config_revision) : null,
        sourcePackageId: row.source_package_id,
      }
    : null
}

export async function getProjectPackageItemObjectKey(params: {
  itemId: number
  projectId: number
}) {
  return (await getProjectPackageItemDownloadSource(params))?.objectKey ?? ''
}

export async function exportProjectPackageTimeline(projectId: number, eventId?: number) {
  const projectResult = await query<{
    owner_display_name: string
    owner_email: string
    project_name: string
  }>(
    `
    select p.name as project_name,
           owner.email as owner_email,
           owner.display_name as owner_display_name
    from projects p
    join users owner on owner.id = p.user_id
    where p.id = $1
    `,
    [projectId],
  )
  const project = projectResult.rows[0]
  if (!project) throw new Error('Project not found')

  const timeline = await getProjectPackageTimeline(projectId)
  const relatedTodoDetailsResult = await query<OperationRelatedTodoExportRow>(
    `
    select t.project_package_operation_id as operation_id,
           t.todo_id,
           todo.title as todo_title,
           t.note,
           operation_author.display_name as operation_note_author_display_name,
           operation_author.email as operation_note_author_email,
           author.display_name as note_author_display_name,
           author.email as note_author_email
    from project_package_operation_todos t
    join project_package_operations o on o.id = t.project_package_operation_id
    join project_package_events e on e.id = o.project_package_event_id
    join todos todo on todo.id = t.todo_id
    left join users operation_author on operation_author.id = t.note_author_user_id
    left join todo_notes note on note.todo_id = t.todo_id
      and note.source_operation_id = o.id
    left join users author on author.id = note.author_user_id
    where e.project_id = $1
    order by t.created_at asc, t.todo_id asc
    `,
    [projectId],
  )
  const relatedTodoDetailsByOperation = new Map<number, OperationRelatedTodoExportDetail[]>()
  for (const row of relatedTodoDetailsResult.rows) {
    const operationId = Number(row.operation_id)
    const details = relatedTodoDetailsByOperation.get(operationId) ?? []
    details.push({
      todoId: Number(row.todo_id),
      title: decryptText(row.todo_title),
      note: row.note ? decryptText(row.note) : '',
      noteAuthorName:
        row.operation_note_author_display_name ??
        row.operation_note_author_email ??
        row.note_author_display_name ??
        row.note_author_email ??
        '',
    })
    relatedTodoDetailsByOperation.set(operationId, details)
  }
  const projectName = decryptText(project.project_name)
  const ownerName = project.owner_display_name || project.owner_email.split('@')[0] || project.owner_email
  const selectedEvent = eventId == null
    ? null
    : timeline.events.find((event) => event.id === eventId) ?? null
  if (eventId != null && !selectedEvent) throw new Error('Event not found')
  const sourceRevisions = new Set(
    (selectedEvent ? [selectedEvent] : timeline.events)
      .flatMap((event) => event.groups)
      .flatMap((group) => group.items)
      .flatMap((item) => item.sourceConfigRevision ? [item.sourceConfigRevision] : []),
  )
  const rulesByRevision = new Map<number, readonly PackageMarketRule[]>()
  await Promise.all([...sourceRevisions].map(async (revision) => {
    const rules = await getPackageMarketRulesForConfigRevision(revision)
    if (rules) rulesByRevision.set(revision, rules)
  }))
  const markdown = selectedEvent
    ? [
      `# ${textValue(projectName, '未命名项目')} · ${textValue(selectedEvent.title, '未命名事件')} 时间线`,
      ...buildProjectPackageEventMarkdown(selectedEvent, relatedTodoDetailsByOperation, rulesByRevision),
      '',
    ].join('\n')
    : buildProjectPackageTimelineMarkdown(
      projectName,
      ownerName,
      timeline,
      relatedTodoDetailsByOperation,
      rulesByRevision,
    )
  const timestamp = formatExportDateTimeForFileName(new Date())
  const fileName = sanitizeExportFileName(
    `${projectName}-${selectedEvent ? selectedEvent.title : '项目'}时间线-${timestamp}.md`,
  )

  return { fileName, markdown }
}

export async function queryRows<T extends QueryResultRow = QueryResultRow>(
  text: string,
  params: unknown[] = [],
) {
  return query<T>(text, params)
}

function extractMentionNames(value: string) {
  return Array.from(value.matchAll(/@([^\s@，。；：、,.!?！？()（）【】[\]<>《》"'“”]+)(?=$|[\s，。；：、,.!?！？()（）【】[\]<>《》"'“”])/g))
    .map((match) => match[1]?.trim() ?? '')
    .filter(Boolean)
}

export async function resolvePackageEventMentionUserIds(projectId: number, content: string) {
  const names = extractMentionNames(content).map((name) => name.toLocaleLowerCase('zh-CN'))
  if (names.length === 0) return []
  const result = await query<{ id: string }>(
    `
    select u.id
    from users u
    where lower(coalesce(nullif(u.display_name, ''), u.email)) = any($2::text[])
      and (
        u.id = (select p.user_id from projects p where p.id = $1)
        or exists (
          select 1 from project_memberships pm
          where pm.project_id = $1 and pm.invited_user_id = u.id and pm.status = 'active'
        )
        or exists (
          select 1 from projects p
          join organization_memberships om on om.organization_id = p.organization_id
          where p.id = $1 and om.user_id = u.id and om.status = 'active'
        )
      )
    `,
    [projectId, names],
  )
  return result.rows.map((row) => Number(row.id))
}

export async function createProjectPackageEventComment(params: {
  authorUserId: number
  content: string
  eventId: number
  mentionedUserIds: number[]
  projectId: number
}) {
  return withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.authorUserId, 'canComment', { eventId: params.eventId })
    const event = await client.query(
      'select id from project_package_events where id = $1 and project_id = $2',
      [params.eventId, params.projectId],
    )
    if (!event.rows[0]) throw new ProjectPackageEventError('Event not found', 404)
    const inserted = await client.query<{ id: string }>(
      `insert into project_package_event_comments (project_package_event_id, author_user_id, content)
       values ($1, $2, $3)
       returning id`,
      [params.eventId, params.authorUserId, encryptText(params.content)],
    )
    const commentId = Number(inserted.rows[0].id)
    await client.query(
      `insert into notification_deliveries (
         user_id,
         kind,
         source_id,
         channel,
         target_type,
         target_id,
         status,
         delivered_at,
         updated_at
       )
       select recipient.user_id,
              'package_event_comment_added',
              $1::bigint,
              'in_app',
              'user',
              recipient.user_id::text,
              'sent',
              now(),
              now()
       from unnest($2::bigint[]) as recipient(user_id)
       where recipient.user_id <> $3::bigint
       on conflict (kind, source_id, channel, target_type, target_id) do update
         set user_id = excluded.user_id,
             status = 'sent',
             attempts = 0,
             last_error = '',
             delivered_at = now(),
             updated_at = now()`,
      [commentId, params.mentionedUserIds, params.authorUserId],
    )
    return commentId
  })
}

async function lockPackageEventComment(
  commentId: number,
  projectId: number,
  userId: number,
  client: PoolClient,
) {
  const locked = await client.query<{ author_user_id: string | null }>(
    `select c.author_user_id
     from project_package_event_comments c
     join project_package_events e on e.id = c.project_package_event_id
     where c.id = $1 and e.project_id = $2
     for update of c`,
    [commentId, projectId],
  )
  const comment = locked.rows[0]
  if (!comment) throw new ProjectPackageEventError('Comment not found', 404)
  if (!comment.author_user_id || Number(comment.author_user_id) !== userId) {
    throw new ProjectPackageEventError('Only the comment author can change it', 403)
  }
  return comment
}

export async function updateProjectPackageEventComment(params: {
  eventId: number
  commentId: number
  content: string
  projectId: number
  userId: number
}) {
  await withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.userId, 'canComment', { commentId: params.commentId, eventId: params.eventId })
    await lockPackageEventComment(params.commentId, params.projectId, params.userId, client)
    await client.query(
      `update project_package_event_comments
       set content = $1, updated_at = now()
       where id = $2`,
      [encryptText(params.content), params.commentId],
    )
  })
}

export async function deleteProjectPackageEventComment(params: {
  eventId: number
  commentId: number
  projectId: number
  userId: number
}) {
  await withTransaction(async (client) => {
    await authorizeDelivery(client, params.projectId, params.userId, 'canComment', { commentId: params.commentId, eventId: params.eventId })
    await lockPackageEventComment(params.commentId, params.projectId, params.userId, client)
    await client.query(
      `delete from notification_states
       where kind = 'package_event_comment_added' and source_id = $1`,
      [params.commentId],
    )
    await client.query(
      `delete from notification_deliveries
       where kind = 'package_event_comment_added' and source_id = $1`,
      [params.commentId],
    )
    await client.query(
      'delete from project_package_event_comments where id = $1',
      [params.commentId],
    )
  })
}
